/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        secondary: {
          DEFAULT: '#855300',
          container: '#fea619',
          fixed: '#ffddb8',
          'fixed-dim': '#ffb95f',
        },
        surface: {
          DEFAULT: '#f8f9ff',
          dim: '#cbdbf5',
          bright: '#f8f9ff',
          'container-low': '#eff4ff',
          'container': '#e5eeff',
          'container-high': '#dce9ff',
          'container-highest': '#d3e4fe',
          'container-lowest': '#ffffff',
          tint: '#515f78',
          variant: '#d3e4fe',
        },
        background: '#f8f9ff',
        primary: {
          DEFAULT: '#000000',
          fixed: '#d6e3ff',
          'fixed-dim': '#b9c7e4',
          container: '#0d1c32',
        },
        tertiary: {
          DEFAULT: '#000000',
          container: '#1a1c1c',
          fixed: '#e2e2e2',
          'fixed-dim': '#c6c6c7',
        },
        outline: {
          DEFAULT: '#75777e',
          variant: '#c5c6cd',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        inverse: {
          surface: '#213145',
          'on-surface': '#eaf1ff',
          primary: '#b9c7e4',
        },
        on: {
          background: '#0b1c30',
          surface: '#0b1c30',
          'surface-variant': '#44474d',
          primary: '#ffffff',
          'primary-container': '#0d1c32',
          'primary-fixed': '#0d1c32',
          'primary-fixed-variant': '#39475f',
          secondary: '#ffffff',
          'secondary-container': '#684000',
          'secondary-fixed': '#2a1700',
          'secondary-fixed-variant': '#653e00',
          tertiary: '#ffffff',
          'tertiary-container': '#838484',
          'tertiary-fixed': '#1a1c1c',
          'tertiary-fixed-variant': '#454747',
          error: '#ffffff',
          'error-container': '#93000a',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '8px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        gutter: '24px',
        'container-max': '1280px',
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Montserrat', 'sans-serif'],
        display: ['Montserrat', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-caps': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.1em', textTransform: 'uppercase' }],
        'label-caps-sm': ['0.625rem', { lineHeight: '0.875rem', letterSpacing: '0.1em', textTransform: 'uppercase' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem' }],
        'headline-sm': ['1rem', { lineHeight: '1.5rem', fontWeight: '500' }],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '500' }],
        'headline-lg': ['1.5rem', { lineHeight: '2rem', fontWeight: '500' }],
        'display-lg-mobile': ['2.25rem', { lineHeight: '2.5rem', fontWeight: '700' }],
        'display-lg': ['3rem', { lineHeight: '3.25rem', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
